name: Deploy to GitHub Pages

on:
  push:
    branches: [dev]  # OR repository_dispatch, schedule, etc.
    paths:
      - 'frontend/**'  # Only trigger on changes in the frontend directory
      - 'frontend/src/data/projectIndex.json'  # Only trigger on changes in the project index

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build the site
        working-directory: frontend
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build  # <--- this is the important change
          publish_branch: gh-pages
